### PR TITLE
1.0.0

### PR DESCRIPTION
**Pull request by caspervonb**
Majority of what is to become 1.0 is complete, tracking further progress with documentation and polish here.

- [x] Make the public interface more cohesive
- [x] Rewrite amok.1 manage, use a more neutral markdown dialect
- [x] Redirect browser and compiler output
- [x] Formalize short hand options (shorthands are a bit, ad-hoc random, want to reserve --port --host for multiplexer)
- [x] Make tests pass on Linux
- [x] Make tests pass on OS X
- [x] Make tests pass on Windows

- [x] Write preliminary API docs 
- [x] Write man/readme.md to serve as an index to the manuals

### CODE REVIEW

**Comment by barneycarroll** [comment]
Wahey! Need any help?

**Comment by caspervonb** [comment]
@barneycarroll proof reading? :wink:

**Comment by caspervonb** [comment]
First pass at the documentation 'done', still needs to be better phrase, some parts are lacking in detail, but atlas it's not an empty directory. Will be iterating further after the other pending items are done.

**Comment by caspervonb** [comment]
Fixed windows search paths in https://github.com/caspervonb/node-browser_process/commit/8bab75efe2b0a6b08aef3944fc430bb09e504ec0

Currently, tests on windows stall on the first test

**Comment by caspervonb** [comment]
Decided to drop the verbose logging mode, since all it was doing was self diagnostics which is better suited to util.debuglog.

**Comment by caspervonb** [comment]
Mostly passing on windows, a couple of false negative with the test/compiler.js tests because of the newline differences.

**Pull request closed without merging**
