### PR TITLE
Log an error when running amok with non-existent input files

### PR DESCRIPTION
**Pull request by SAMdroid-apps**

### CODE REVIEW

**Comment by SAMdroid-apps** [comment]
I forced pushed a version that lives in `cmd.js`.  It only logs the first use case ('input file was not found')

**Comment by caspervonb** [comment]
So I've just landed a bole based log in a349f6e660f48de08815a18ed587365ed2cda03c

**Comment by SAMdroid-apps** [comment]
Awesome!  I will look into bole and have look at making this patch use bole!

**Comment by caspervonb** [comment]
Moving target, sorry :)

**Pull request closed without merging**
